services:
  - type: web
    name: agentic-backend
    runtime: node
    buildCommand: cd Backend && npm install
    startCommand: cd Backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: mongodb+srv://akshaysanaka07_db_user:HZMvpmlJrQlHDpWJ@cluster0.vl01zdp.mongodb.net/?appName=Cluster0
      - key: PORT
        value: 10000
  - type: web
    name: agentic-frontend
    runtime: static
    buildCommand: cd Frontend && npm install && npm run build
    staticPublishPath: Frontend/dist
    envVars:
      - key: NODE_ENV
        value: production
